# Generated by Django 5.2.1 on 2025-06-08 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0004_product_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='country',
        ),
    ]
